import type { AssetClass, MacroTheme } from "@prisma/client";

export const MACRO_THEME_KEYWORDS: Record<MacroTheme, string[]> = {
  inflation: [
    "inflation",
    "cpi",
    "pce",
    "ppi",
    "price pressure",
    "consumer prices",
    "sticky prices",
    "disinflation",
  ],
  interest_rates: [
    "interest rate",
    "interest rates",
    "rate hike",
    "rate cut",
    "fed hike",
    "tightening",
    "easing",
    "yield",
    "policy rate",
    "hawkish",
    "dovish",
  ],
  recession_growth: [
    "recession",
    "growth",
    "gdp",
    "slowdown",
    "expansion",
    "consumer demand",
    "industrial production",
    "retail sales",
    "housing starts",
  ],
  labor_market: [
    "labor market",
    "labour market",
    "jobs",
    "employment",
    "unemployment",
    "payroll",
    "wages",
    "job openings",
    "claims",
  ],
  liquidity_credit: [
    "liquidity",
    "credit",
    "bank lending",
    "loan growth",
    "balance sheet",
    "funding stress",
    "reserves",
    "repo",
    "credit conditions",
  ],
  energy_oil: [
    "oil",
    "crude",
    "energy",
    "gasoline",
    "natural gas",
    "opec",
    "brent",
    "wti",
  ],
  china_growth: [
    "china",
    "beijing",
    "pboc",
    "property sector",
    "yuan",
    "chinese economy",
    "stimulus",
  ],
  trade_policy: [
    "tariff",
    "trade policy",
    "trade war",
    "export control",
    "import restriction",
    "sanction",
    "wto",
    "entity list",
  ],
  financial_regulation: [
    "regulation",
    "regulatory",
    "capital rules",
    "bank capital",
    "compliance",
    "supervision",
    "sec",
    "fca",
    "prudential",
  ],
};

export const THEME_PRIORITY: MacroTheme[] = [
  "interest_rates",
  "inflation",
  "recession_growth",
  "labor_market",
  "liquidity_credit",
  "energy_oil",
  "china_growth",
  "trade_policy",
  "financial_regulation",
];

export const THEME_ASSET_CLASS: Record<MacroTheme, AssetClass> = {
  inflation: "BOND",
  interest_rates: "BOND",
  recession_growth: "STOCK",
  labor_market: "STOCK",
  liquidity_credit: "BOND",
  energy_oil: "COMMODITY",
  china_growth: "FOREX",
  trade_policy: "FOREX",
  financial_regulation: "STOCK",
};

export const MACRO_SERIES_THEME_MAP: Record<string, MacroTheme[]> = {
  CPIAUCSL: ["inflation"],
  CPILFESL: ["inflation"],
  PCEPI: ["inflation"],
  PCEPILFE: ["inflation"],
  PPIACO: ["inflation"],
  CES0500000003: ["labor_market", "inflation"],
  DFF: ["interest_rates"],
  DGS2: ["interest_rates"],
  T10Y2Y: ["interest_rates", "recession_growth"],
  DFII10: ["interest_rates", "inflation"],
  PAYEMS: ["labor_market"],
  UNRATE: ["labor_market", "recession_growth"],
  ICSA: ["labor_market"],
  JTSJOL: ["labor_market"],
  CIVPART: ["labor_market"],
  A191RL1Q225SBEA: ["recession_growth"],
  RSAFS: ["recession_growth"],
  INDPRO: ["recession_growth"],
  UMCSENT: ["recession_growth"],
  HOUST: ["recession_growth", "interest_rates"],
  PERMIT: ["recession_growth", "interest_rates"],
  BUSLOANS: ["liquidity_credit"],
  USREC: ["recession_growth"],
  WALCL: ["liquidity_credit", "interest_rates"],
};
